---

- hosts: webservers
  become: true
  tasks:

  - name: install updates (Redhat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes

  - name: install httpd and php package
    tags: RedHat
    dnf:
      name:
        - httpd
        - php
      state: latest

- hosts: dbserver
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: mariadb
    dnf:
      name: mariadb
      state: latest


