---

- hosts: webservers
  become: true
  tasks:

  - name: install updates (Redhat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes

  - name: install httpd and php package
    tags: RedHat
    dnf:
      name:
        - httpd
        - php
      state: latest

  - name: start httpd (RedHat)
    tags: apache,httpd
    service:
      name: httpd
      state: started
      enabled: yes
  
  - name: change e-mail address for admin
    tags: apache,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin root@localhost
    register: httpd

  - name: restart httpd (RedHat)
    tags: apache,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: RedHat
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: webservers
  become: true
  tasks:

  - name: install unzip
    package:
       name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.3/terraform_1.6.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: dbserver
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: mariadb
    dnf:
      name: mariadb
      state: latest


