---

- hosts: all
  become: true
  tasks:

  - name: install httpd and php package
    package:
      name:
        - "{{ httpd_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

