---

- hosts: all
  become: true
  tasks:
  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Red hat"

  - name: install httpd package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Red hat"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Red hat"
